<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Mapping\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.1.32" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\VendingMachines.Domain.csproj" />
    <ProjectReference Include="..\Shared\VendingMachines.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="PresentationFramework">
      <HintPath>..\..\..\..\..\..\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\PresentationFramework.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
