// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VendingMachines.Infrastructure.Data;

namespace VendingMachines.Infrastructure.Data.Migrations
{
    [DbContext(typeof(VendingMachinesDbContext))]
    partial class VendingMachinesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("VendingMachines.Domain.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Description = "Полный доступ ко всем функциям системы.",
                            DisplayName = "Администратор",
                            SystemName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Description = "Доступ к основным рабочим функциям (обработке заказов/данных).",
                            DisplayName = "Оператор",
                            SystemName = "Operator"
                        },
                        new
                        {
                            RoleId = 3,
                            Description = "Стандартный пользователь системы.",
                            DisplayName = "Пользователь",
                            SystemName = "User"
                        },
                        new
                        {
                            RoleId = 4,
                            Description = "Минимальные права (просмотр публичной информации).",
                            DisplayName = "Гость",
                            SystemName = "Guest"
                        });
                });

            modelBuilder.Entity("VendingMachines.Domain.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(150);

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "Admin@mail.ru",
                            FailedLoginAttempts = 0,
                            FullName = "Администратор",
                            PasswordHash = "$2a$11$WUTkxON8RaqF6Mcedyhbxu4dvdSFrxGSjBeln66g/rcQCxk7In8DC",
                            RoleId = 1,
                            Username = "Admin"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "Operator@yandex.ru",
                            FailedLoginAttempts = 0,
                            FullName = "Опреатор",
                            PasswordHash = "$2a$11$acEuZ0Or73p7DMBzMQAndecUCN7h6igInrYI46fWEJzvGZXPMJWUu",
                            RoleId = 2,
                            Username = "Operator"
                        });
                });

            modelBuilder.Entity("VendingMachines.Domain.Models.User", b =>
                {
                    b.HasOne("VendingMachines.Domain.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
