<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\VendingMachines.Domain.csproj" />
    <ProjectReference Include="..\VendingMachines.Application\VendingMachines.Application.csproj" />
    <ProjectReference Include="..\VendingMachines.DAL\VendingMachines.Infrastructure.csproj" />
  </ItemGroup>

</Project>
